path_classifiers:
  test: "**/*Test.C"
  docs: "docs/Sphinx/source/conf.py"
extraction:
  cpp:
    prepare:
      packages:
      - "wget"
      - "build-essential"
      - "binutils-dev"
      - "cmake"
      - "flex"
      - "zlib1g-dev"
      - "libncurses5-dev"
      - "libiberty-dev"
      - "libxt-dev"
      - "rpm"
      - "mercurial"
      - "graphviz"
      - "python3"
      - "python3-dev"
    after_prepare:
    - "mkdir -p ~/foam"
    - "git clone https://github.com/Unofficial-Extend-Project-Mirror/foam-extend-foam-extend-4.0\
      \ ~/foam/foam-extend-4.0"
    - "source ~/foam/foam-extend-4.0/etc/bashrc"
    - "~/foam/foam-extend-4.0/Allwmake.firstInstall"
    configure:
      command: "source ~/foam/foam-extend-4.0/etc/bashrc"
    index:
      build_command: "./Allwmake"
