git:
  depth: 3
addons:
  apt:
    packages:
      - docker-ce
services:
    - docker

os: linux
language: cpp

script:
  - docker run --rm -u root -v $PWD:/home/foam/OpenRSR foamscience/openrsr /bin/bash -c "/home/foam/OpenRSR/scripts/docker_build.sh"
