git:
  depth: 3
addons:
  apt:
    packages:
      - docker-ce
services:
    - docker

language:
    - c++

script:
  - docker run --name fe4 -v $PWD:/home/foam/foam/OpenRSR foamscience/openrsr /bin/bash -c "echo 'Container instantiated'"
  - docker exec -it fe4 "cd foam/OpenRSR; ./Allwmake"
  - docker exec -it fe4 "cd foam/OpenRSR/solvers/pSwCoupledFoam; wmake"
  - docker exec -it fe4 "cd foam/OpenRSR/tutorials; ls"
