git:
  depth: 3
addons:
  apt:
    packages:
      - docker-ce
services:
    - docker

language: 
  - c++

script:
  - docker run --rm -u root -v $PWD:/home/foam/OpenRSR foamscience/openrsr /bin/bash -c "/home/foam/OpenRSR/scripts/docker_build.sh"
