git:
  depth: 3
addons:
  apt:
    packages:
      - docker-ce
      - curl
      - jq
      - lcov
services:
    - docker

os: linux
language:
  - cpp
  - java

script:
  - docker run --rm -u root -v $PWD:/home/foam/OpenRSR foamscience/openrsr /bin/bash -c "/home/foam/OpenRSR/scripts/docker_build.sh"
  - curl -Ls https://coverage.codacy.com/get.sh | bash -s report -r $PWD/lcov.info
