git:
  depth: 3
addons:
  apt:
    packages:
      - docker-ce
services:
    - docker

language:
    - c++

script:
  - docker run --rm -v $PWD:/home/foam/foam/OpenRSR foamscience/openrsr /bin/bash -c "set -ev; cd foam; ls -la; cd OpenRSR; cd foam"
#    "cd foam/OpenRSR; ./Allwmake;"\
#    "cd foam/OpenRSR/solvers/pSwCoupledFoam; wmake;"\
#    "cd foam/OpenRSR/tutorials; ls;"
