git:
  depth: 3
addons:
  apt:
    packages:
      - docker-ce
services:
    - docker

language:
    - c++

script:
  - docker run --rm -v $PWD:/home/foam/foam/OpenRSR foamscience/openrsr /bin/bash -c "$PWD/.build.sh"
