git:
  depth: 3
addons:
  apt:
    packages:
      - docker-ce
services:
    - docker

language: 
  - c++

script:
  - docker run --rm -v $PWD:/home/foam/OpenRSR foamscience/openrsr /bin/bash -c "./scripts/docker_build.sh"
